### ISSUE TITLE
Where are the cropped images for the TigDog dataset used ?

### ISSUE THREAD

**Issue by YuheD** [VisionLearningGroup/UDA_PoseEstimation#2]

**Comment by wangkaihong** [comment]
Hi, 

They are used here:
https://github.com/VisionLearningGroup/UDA_PoseEstimation/blob/master/lib/datasets/real_animal_all.py

the code is pretty much borrowed from UDA-Animal's repo.

**Comment by wangkaihong** [comment]
Hi,

Sorry for the confusion. The cropped images are not really used as in UDA-Animal. Those original images will be cropped in real-time when being loaded. I have updated the readme.

**Comment by YuheD** [comment]
> Hi,
> 
> Sorry for the confusion. The cropped images are not really used as in UDA-Animal. Those original images will be cropped in real-time when being loaded. I have updated the readme.

Thanks
