### ISSUE TITLE
About "recover_min" and "recover_max"

### ISSUE THREAD

**Issue by huitangtang** [VisionLearningGroup/UDA_PoseEstimation#6]
I highly appreciate that you present a nice work. 

However, I am confused where are "recover_min" and "recover_max" from and how to calculate them. 

Could you please help me understand the above issues?  

Many thanks.

**Comment by wangkaihong** [comment]
Hi,

It should act like a "clipping" function to ensure the values predicted by the stylization network are within a stable range. Unfortunately, I didn't keep the details but the gist is that it should be obtained based on the statistics of the stylization network during the training stage.
